//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.20 at 06:12:49 PM CDT 
//

package net.dynamichorizons.rp.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

/**
 * <p>
 * Java class for DeliveryAvailable complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DeliveryAvailable">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>boolean">
 *       &lt;attribute name="radius" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="fee" type="{http://www.w3.org/2001/XMLSchema}double" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType( XmlAccessType.FIELD )
@XmlType( name = "DeliveryAvailable", propOrder = { "value" } )
public class DeliveryAvailable
{

    @XmlValue
    protected boolean value;

    @XmlAttribute( name = "radius" )
    protected Double radius;

    @XmlAttribute( name = "fee" )
    protected Double fee;

    /**
     * Gets the value of the value property.
     */
    public boolean isValue()
    {
        return value;
    }

    /**
     * Sets the value of the value property.
     */
    public void setValue( boolean value )
    {
        this.value = value;
    }

    /**
     * Gets the value of the radius property.
     * 
     * @return possible object is {@link Double }
     */
    public Double getRadius()
    {
        return radius;
    }

    /**
     * Sets the value of the radius property.
     * 
     * @param value allowed object is {@link Double }
     */
    public void setRadius( Double value )
    {
        this.radius = value;
    }

    /**
     * Gets the value of the fee property.
     * 
     * @return possible object is {@link Double }
     */
    public Double getFee()
    {
        return fee;
    }

    /**
     * Sets the value of the fee property.
     * 
     * @param value allowed object is {@link Double }
     */
    public void setFee( Double value )
    {
        this.fee = value;
    }

}
