//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.20 at 06:12:49 PM CDT 
//

package net.dynamichorizons.rp.domain;

import javax.xml.bind.annotation.adapters.XmlAdapter;
import org.joda.time.LocalTime;

public class LocalTimeXmlAdapter
    extends XmlAdapter<String, LocalTime>
{

    public LocalTime unmarshal( String value )
    {
        return ( net.dynamichorizons.rp.util.DatatypeConverter.parseTime( value ) );
    }

    public String marshal( LocalTime value )
    {
        return ( net.dynamichorizons.rp.util.DatatypeConverter.printTime( value ) );
    }

}
