//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.20 at 06:12:49 PM CDT 
//

package net.dynamichorizons.rp.domain;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for OnlineType.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="OnlineType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="web"/>
 *     &lt;enumeration value="mobile"/>
 *     &lt;enumeration value="web/mobile"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlType( name = "OnlineType" )
@XmlEnum
public enum OnlineType
{

    @XmlEnumValue( "web" )
    WEB( "web" ), @XmlEnumValue( "mobile" )
    MOBILE( "mobile" ), @XmlEnumValue( "web/mobile" )
    WEB_MOBILE( "web/mobile" );
    private final String value;

    OnlineType( String v )
    {
        value = v;
    }

    public String value()
    {
        return value;
    }

    public static OnlineType fromValue( String v )
    {
        for ( OnlineType c : OnlineType.values() )
        {
            if ( c.value.equals( v ) )
            {
                return c;
            }
        }
        throw new IllegalArgumentException( v );
    }

}
