DROP TABLE IF EXISTS TBL_MENU_ITEM_IMAGE;

DROP TABLE IF EXISTS TBL_MENU_ITEM_OPTION_ITEM;
	
DROP TABLE IF EXISTS TBL_MENU_ITEM_OPTION;

DROP TABLE IF EXISTS TBL_MENU_ITEM_SIZE;

DROP TABLE IF EXISTS TBL_MENU_ITEM_TAGS;

DROP TABLE IF EXISTS TBL_MENU_GROUP_ITEM;

DROP TABLE IF EXISTS TBL_MENU_GROUP_OPTION_ITEM;
	
DROP TABLE IF EXISTS TBL_MENU_GROUP_OPTION;

DROP TABLE IF EXISTS TBL_MENU_ITEM;

DROP TABLE IF EXISTS TBL_MENU_GROUP;

DROP TABLE IF EXISTS TBL_MENU;

CREATE TABLE TBL_MENU (
	MENU_UID CHAR(37) NOT NULL UNIQUE,
	MENU_NAME VARCHAR(50) NOT NULL,
	MENU_KEY VARCHAR(50) NOT NULL,
	MENU_DESC VARCHAR(255),
	MENU_NOTE VARCHAR(255),
	MENU_LANGUAGE VARCHAR(2) NOT NULL DEFAULT 'EN',
	MENU_CURRENCY_SYMBOL VARCHAR(3) NOT NULL DEFAULT 'USD',
	MENU_DURATION_NAME VARCHAR(255) NOT NULL,
	MENU_DURATION_END_TIME INTEGER UNSIGNED,
	MENU_DURATION_START_TIME INTEGER UNSIGNED,
	OPTLOCK INTEGER,
	PRIMARY KEY (MENU_UID)
) ENGINE=InnoDB;

CREATE TABLE TBL_MENU_GROUP (
	MENU_GROUP_UID CHAR(37) NOT NULL UNIQUE,
	MENU_GROUP_NAME VARCHAR(50),
	MENU_GROUP_DESC VARCHAR(255),
	MENU_GROUP_NOTE VARCHAR(255),
	IS_DISABLED BOOLEAN DEFAULT '0',
	ORDER_BY INTEGER NOT NULL DEFAULT '0',
	OPTLOCK INTEGER,
	MENU_UID CHAR(37) NOT NULL,
	PRIMARY KEY (MENU_GROUP_UID)
) ENGINE=InnoDB;

CREATE TABLE TBL_MENU_GROUP_OPTION (
	MENU_GROUP_OPTION_ID SERIAL,
	MENU_GROUP_OPTION_NAME VARCHAR(50),
	MENU_GROUP_OPTION_INFO VARCHAR(255),
	MENU_GROUP_OPTION_MAX_SELECTED INTEGER UNSIGNED,
	MENU_GROUP_OPTION_MIN_SELECTED INTEGER UNSIGNED,
	OPTLOCK INTEGER,
	MENU_GROUP_UID CHAR(37),
	PRIMARY KEY (MENU_GROUP_OPTION_ID)
) ENGINE=InnoDB;

CREATE TABLE TBL_MENU_GROUP_OPTION_ITEM (
	MENU_GROUP_OPTION_ITEM_ID SERIAL,
	MENU_GROUP_OPTION_ITEM_NAME VARCHAR(50),
	MENU_GROUP_OPTION_ITEM_ADDL_COST DECIMAL(19,4),
	OPTLOCK INTEGER,
	MENU_GROUP_OPTION_ID BIGINT UNSIGNED NOT NULL,
	PRIMARY KEY (MENU_GROUP_OPTION_ITEM_ID)
) ENGINE=InnoDB;

CREATE TABLE TBL_MENU_GROUP_ITEM (
	MENU_GROUP_ITEM_ID SERIAL,
	MENU_GROUP_UID CHAR(37) NOT NULL, 
	MENU_ITEM_UID CHAR(37) NOT NULL, 
	MENU_GROUP_ITEM_PRICE DECIMAL(19,4),
	OPTLOCK INTEGER,
	PRIMARY KEY (MENU_GROUP_ITEM_ID)
) ENGINE=InnoDB;

CREATE TABLE TBL_MENU_ITEM (
	MENU_ITEM_UID CHAR(37) NOT NULL UNIQUE,
	MENU_ITEM_NAME VARCHAR(75),
	MENU_ITEM_DESC VARCHAR(450),
	MENU_ITEM_ALLERGENS VARCHAR(255),
	MENU_ITEM_ALLERGY_INFORMATION VARCHAR(450),
	MENU_ITEM_CALORIES INTEGER,
	MENU_ITEM_HEAT_INDEX INTEGER,
	IS_DISABLED  BOOLEAN DEFAULT '0',
	IS_SPECIAL  BOOLEAN DEFAULT '0',
	IS_GLUTEN_FREE  BOOLEAN DEFAULT '0',
	IS_HALAL  BOOLEAN DEFAULT '0',
	IS_KOSHER  BOOLEAN DEFAULT '0',
	IS_VEGAN  BOOLEAN DEFAULT '0',
	IS_VEGETARIAN  BOOLEAN DEFAULT '0',
	OPTLOCK INTEGER,
	PRIMARY KEY (MENU_ITEM_UID)
) ENGINE=InnoDB;

CREATE TABLE TBL_MENU_ITEM_IMAGE (
	MENU_ITEM_IMAGE_ID SERIAL,
	MENU_ITEM_IMAGE_MEDIA VARCHAR(50) NOT NULL,
	MENU_ITEM_IMAGE_TYPE VARCHAR(50) NOT NULL,
	MENU_ITEM_IMAGE_WIDTH INTEGER,
	MENU_ITEM_IMAGE_HEIGHT INTEGER,
	OPTLOCK INTEGER,
	MENU_GROUP_ITEM_ID BIGINT UNSIGNED NOT NULL,
	PRIMARY KEY (MENU_ITEM_IMAGE_ID)
) ENGINE=InnoDB;

CREATE TABLE TBL_MENU_ITEM_OPTION (
	MENU_ITEM_OPTION_ID SERIAL,
	MENU_ITEM_OPTION_NAME VARCHAR(50) NOT NULL,
	MENU_ITEM_OPTION_INFO VARCHAR(255),
	MENU_ITEM_OPTION_MIN_SELECTED INTEGER,
	MENU_ITEM_OPTION_MAX_SELECTED INTEGER,
	OPTLOCK INTEGER,
	MENU_GROUP_ITEM_ID BIGINT UNSIGNED NOT NULL,
	PRIMARY KEY (MENU_ITEM_OPTION_ID)
) ENGINE=InnoDB;

CREATE TABLE TBL_MENU_ITEM_OPTION_ITEM (
	MENU_ITEM_OPTION_ITEM_ID SERIAL,
	MENU_ITEM_OPTION_ITEM_NAME VARCHAR(255),
	MENU_ITEM_OPTION_ITEM_ADDL_COST DECIMAL(19,4),
	OPTLOCK INTEGER,
	MENU_ITEM_OPTION_ID BIGINT UNSIGNED NOT NULL,
	PRIMARY KEY (MENU_ITEM_OPTION_ITEM_ID)
) ENGINE=InnoDB;

CREATE TABLE TBL_MENU_ITEM_SIZE (
	MENU_ITEM_SIZE_ID SERIAL,
	MENU_ITEM_SIZE_NAME VARCHAR(25) NOT NULL,
	MENU_ITEM_SIZE_DESC VARCHAR(120),
	MENU_ITEM_SIZE_CALORIES INTEGER,
	MENU_ITEM_SIZE_PRICE DECIMAL(19,4),
	OPTLOCK INTEGER,
	MENU_GROUP_ITEM_ID BIGINT UNSIGNED NOT NULL,
	PRIMARY KEY (MENU_ITEM_SIZE_ID)
) ENGINE=InnoDB;

CREATE TABLE TBL_MENU_ITEM_TAGS (
	MENU_ITEM_UID CHAR(37) NOT NULL,
	MENU_ITEM_TAG VARCHAR(64)
) ENGINE=InnoDB;

ALTER TABLE TBL_MENU_GROUP 
	ADD INDEX FK_MENU_GROUP (MENU_UID), 
	ADD CONSTRAINT FK_MENU_GROUP 
	FOREIGN KEY (MENU_UID) 
	REFERENCES TBL_MENU (MENU_UID);

ALTER TABLE TBL_MENU_GROUP_OPTION 
	ADD INDEX FK_MENU_GROUP_OPTION (MENU_GROUP_UID), 
	ADD CONSTRAINT FK_MENU_GROUP_OPTION 
	FOREIGN KEY (MENU_GROUP_UID) 
	REFERENCES TBL_MENU_GROUP (MENU_GROUP_UID);

ALTER TABLE TBL_MENU_GROUP_OPTION_ITEM 
	ADD INDEX FK_MENU_GROUP_OPTION_ITEM (MENU_GROUP_OPTION_ID), 
	ADD CONSTRAINT FK_MENU_GROUP_OPTION_ITEM 
	FOREIGN KEY (MENU_GROUP_OPTION_ID) 
	REFERENCES TBL_MENU_GROUP_OPTION (MENU_GROUP_OPTION_ID);
	
ALTER TABLE TBL_MENU_GROUP_ITEM
	ADD INDEX FK_MENU_GROUP_ITEM (MENU_GROUP_UID, MENU_ITEM_UID),
	ADD CONSTRAINT FK_MENU_GROUP_ITEM_GROUP
		FOREIGN KEY (MENU_GROUP_UID)
		REFERENCES TBL_MENU_GROUP (MENU_GROUP_UID),
	ADD CONSTRAINT FK_MENU_GROUP_ITEM_ITEM
		FOREIGN KEY (MENU_ITEM_UID)
		REFERENCES TBL_MENU_ITEM (MENU_ITEM_UID);

ALTER TABLE TBL_MENU_ITEM_IMAGE 
	ADD INDEX FK_MENU_ITEM_IMAGE (MENU_GROUP_ITEM_ID), 
	ADD CONSTRAINT FK_MENU_ITEM_IMAGE 
	FOREIGN KEY (MENU_GROUP_ITEM_ID) 
	REFERENCES TBL_MENU_GROUP_ITEM (MENU_GROUP_ITEM_ID);

ALTER TABLE TBL_MENU_ITEM_OPTION 
	ADD INDEX FK_MENU_ITEM_OPTION (MENU_GROUP_ITEM_ID), 
	ADD CONSTRAINT FK_MENU_ITEM_OPTION 
	FOREIGN KEY (MENU_GROUP_ITEM_ID) 
	REFERENCES TBL_MENU_GROUP_ITEM (MENU_GROUP_ITEM_ID);

ALTER TABLE TBL_MENU_ITEM_OPTION_ITEM 
	ADD INDEX FK_MENU_ITEM_OPTION_ITEM (MENU_ITEM_OPTION_ID), 
	ADD CONSTRAINT FK_MENU_ITEM_OPTION_ITEM 
	FOREIGN KEY (MENU_ITEM_OPTION_ID) 
	REFERENCES TBL_MENU_ITEM_OPTION (MENU_ITEM_OPTION_ID);

ALTER TABLE TBL_MENU_ITEM_SIZE 
	ADD INDEX FK_MENU_ITEM_SIZE (MENU_GROUP_ITEM_ID), 
	ADD CONSTRAINT FK_MENU_ITEM_SIZE
	FOREIGN KEY (MENU_GROUP_ITEM_ID) 
	REFERENCES TBL_MENU_GROUP_ITEM (MENU_GROUP_ITEM_ID);

ALTER TABLE TBL_MENU_ITEM_TAGS 
	ADD INDEX FK_MENU_ITEM_TAGS (MENU_ITEM_UID), 
	ADD CONSTRAINT FK_MENU_ITEM_TAGS
	FOREIGN KEY (MENU_ITEM_UID) 
	REFERENCES TBL_MENU_ITEM (MENU_ITEM_UID);